services:

  service-c:
    build: ./services/service-c
    ports:
      - "5002:5002"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 10s
      timeout: 3s
      retries: 3

  service-b:
    build: ./services/service-b
    ports:
      - "5001:5001"
    depends_on:
      - service-c
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 10s
      timeout: 3s
      retries: 3

  service-a:
    build: ./services/service-a
    ports:
      - "5000:5000"
    depends_on:
      - service-b
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 3s
      retries: 3
