apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c
spec:
  replicas: 1

  selector:
    matchLabels:
      app: service-c

  template:
    metadata:
      labels:
        app: service-c
    
    spec:
      containers:
      - name: service-c
        image: research-app-service-c:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5002

        livenessProbe:
          httpGet:
            path: /health
            port: 5002
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /data
            port: 5002
          initialDelaySeconds: 2
          periodSeconds: 3
          