apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c
spec:
  replicas: 1

  selector:
    matchLabels:
      app: service-c

  template:
    metadata:
      labels:
        app: service-c
    
    spec:
      containers:
      - name: service-c
        image: research-app-service-c:latest
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 5002
